### ISSUE TITLE
Page profil

### ISSUE THREAD

**Issue by nk-fouque** [tomatrocho/insapp-material#1]
Ce serait bien plus ergonomique de modifier les infos du profil dans l'onglet profil, séparé des paramètres de notification, en plus sinon l'onglet profil ne sert à rien

**Comment by thomas-bouvier** [comment]
Salut @nk-fouque et merci pour ta contribution.

Il serait en effet pertinent de séparer l'édition du profil de l'écran des paramètres. Actuellement, tout est centralisé pour des raisons pratiques : la [librairie Preference](https://developer.android.com/reference/androidx/preference/package-summary) permet d'automatiser la persistance des données dans les `SharedPreferences`.

Nous réfléchissons à améliorer l'ergonomie, peut-être effectivement en permettant l'édition du profil sur la page profil.

La fonction principale de l'onglet profil est de lister les évènements auxquels l'utilisateur veut participer.

Je ferme l'issue, n'hésite pas à la rouvrir si tu as des suggestions !
